"""Chat schemas — request/response models for the chat endpoint."""

from typing import Literal

from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """A single message in the conversation history."""

    role: str  # "user" or "assistant"
    content: str


class ChatRequest(BaseModel):
    """Incoming chat request from the widget."""

    message: str
    session_id: str
    history: list[ChatMessage] = []


class ChatbotResponse(BaseModel):
    """
    Structured response generated by the RAG pipeline.
    Updated for high resilience across different LLM providers (Gemini/Claude).
    """

    answer: str = Field(
        description="Direct answer to the question using context."
    )

    was_answered: bool = Field(
        default=True,
        description="True if context contained information."
    )

    confidence: str = Field(
        default="medium",
        description="high, medium, or low confidence level."
    )

    sources: list[str] = Field(
        default=[],
        description="Source names used to answer."
    )

    follow_up_questions: list[str] = Field(
        default=[],
        description="Suggested follow-up questions."
    )

    response_type: str = Field(
        default="answer",
        description="answer, partial, or fallback."
    )

    tokens_used: int = 0
    refresh_token: bool = False
